name: BarkCraftMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for BarkFreedom.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [CPacket, darkwolfXST]

# plugin.yml is no longer used to define commands.
